spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wardRobe
    username: postgres
    password: slap4msth
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
